apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newssummariser-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - news.deestore.in
    secretName: newssummariser-tls
  rules:
  - host: news.deestore.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: newssummariser-service
            port:
              number: 8501  # Streamlit port

