apiVersion: v1
kind: Service
metadata:
  name: newssummariser-service
  labels:
    app: newssummariser
spec:
  type: NodePort  # Use NodePort for minikube instead of LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: api
    nodePort: 30081  # Access via minikube IP:30081
  selector:
    app: newssummariser

